### ISSUE TITLE
Crash Report -1737316008

### ISSUE THREAD

**Issue by joeuk147** [wowsims/classic#64] opened 2024-12-31 16:09 UTC
Link:
https://wowsims.github.io/classic/warrior/#eJzj4uBgEmByYEpgdOKRYHRgDGCKYMxg9GAUYpB6zMbFFpCTWJlaJMCqwKmVwcUm8CBJ4hE3F7PA5gog8T8FSLyKAgqfi5Z4zAekO1Il7oLo66US89mBku25QM61UpAeNoHuJIl+kOCqNC4WgY1djEDm8hgg0QtStCFJ4g0fFwOQ+zbJSFiASYJRg9GAsYBjBiPjCkaWB4yMVvdYuB4wMYwCmgKhH4wD7YSBAq+YGJy4LEA5gDGCMYHRy8zAyNjA1MDI0NjUyMAQyDI01DU1NTAwMDQ2NDAAMYBA1wAdAPMPSxJDFjABF5xgPAlNsBwOF6EsS4cbTIyzGBlWMbFJsUgwWjArHWDmhEjFOQhCGHoOkrNmgsBJe0uIyAV7xTQwuGZvNIGZ40YTrxCHT2pZao6CmYGEvdYgyxcanQ5UMUdtLUXmCEj9p447gMAQTBYsd7DMzP/QejLkqr0jVMYhghEATM5aMg==

RNG Seed: 287375205

Tried to add new aura in a finalized environment!
Stack Trace:
goroutine 28 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/classic/sim/core.runSim.func1()
	/home/runner/work/classic/classic/sim/core/sim.go:125 +0x10
panic({0xa4900, 0x290458})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/classic/sim/core.(*auraTracker).registerAura(0x31326b8, 0x3132000, {{0x3a3be78, 0x13}, {0x0, 0x0}, {0x40d6, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/classic/classic/sim/core/aura.go:376 +0x43
github.com/wowsims/classic/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/classic/classic/sim/core/aura.go:416
github.com/wowsims/classic/sim/core.(*Unit).GetOrRegisterAura(0x3132000, {{0x3a3be78, 0x13}, {0x0, 0x0}, {0x40d6, 0x0, 0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/classic/classic/sim/core/aura.go:422 +0x2f
github.com/wowsims/classic/sim...

**Comment by kayla-glick** [comment] 2024-12-31 23:15
Caused by the weapon https://www.wowhead.com/classic/item=12592/blackblade-of-shahram due to how we coded the buff auras. There was a similar issue in the SoD repo recently so I'm porting the code over

**Comment by kayla-glick** [comment] 2024-12-31 23:18
Shipping a fix for this now

**Closed by kayla-glick** 2024-12-31 23:18 UTC
Labels: bug, items
